version: '2.1'

services:
  base_recserver:
    build: .
    volumes:
      - /data/groupLe_recsys/processed:/data/groupLe_recsys/processed
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python3", "./healthcheck.py" ]
      interval: 10s
      timeout: 5s
      retries: 5